### ISSUE TITLE
Pymol Freeze

### ISSUE THREAD

**Issue by mayank-kohli** [brendaferrari/PORCUPINEplot#1]
Hi, 

I am facing a problem, when I am trying to run the script.pml the pymol window open but it remains stuck. 
The pymol screen will be blank and it remains like that.
Have you ever faced that?
Is there any possible solution?

Thanks

**Comment by brendaferrari** [comment]
Hello!

Depending on the size of your simulation, pymol may take a bit longer to run the calculations. The pymol interface screen freezes while the calculation is being run. I suggest for you to test the script with a short simulation or wait a bit longer for the calculation on your simulation to run. If the problem persists, feel free to send another message on this thread, I am going to leave it open.
